server:
  port: 8888

spring:
  datasource:
    name: test
    url: jdbc:mysql://127.0.0.1:3306/cloud?characterEncoding=utf8&useSSL=true
    username: root
    password: a123
    # 使用druid数据源
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    useSSL: false
    filters: stat
    maxActive: 20
    initialSize: 1
    maxWait: 60000
    minIdle: 1
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: select 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxOpenPreparedStatements: 20
  thymeleaf:
    prefix: classpath:/templates/
    ## 实现页面热部署，修改后立即生效
    cache: false
    suffix: .html
    encoding: utf-8
    servlet:
      content-type: text/html
  ## 热部署生效
  devtools:
    restart:
      enabled: true
      exclude: templates
  application:
    name: boot-client
  # 消息队列配置
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: admin
    password: a123
    #指定连接到broker的virtual host
    virtual-host: /
    #指定最小的消费者数量
    listener:
      simple:
        concurrency: 5
        max-concurrency: 10
        # 指定Acknowledge的模式，我这里是手工确认的
        acknowledge-mode: manual
        # 指定一个请求能处理多少个消息，如果有事务的话，必须大于等于transaction数量
        prefetch: 1
    #指定最大的消费者数量
 #邮件发送的配置
  mail:
    host: smtp.qq.com
    username: 993874575@qq.com
    password: tqrdzuxcdgrobdjh
    default-encoding: UTF-8
  mvc:
    static-path-pattern: /static/**
  resources:
    static-locations: classpath:/static,classpath:/resources
## 该配置节点为独立的节点，容易将这个配置放在spring的节点下，导致配置无法被识别
mybatis:
  mapper-locations: classpath:mapping/**/*.xml #注意：一定要对应mapper映射xml文件的所在路径
  type-aliases-package: com.zys.boot  # 注意：对应实体类的路径

#pagehelper分页插件
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
