server:
  port: 8888

spring:
  datasource:
    name: test
    url: jdbc:mysql://127.0.0.1:3309/cloud2?characterEncoding=utf8&useSSL=true
    username: root
    password: a123
    # 使用druid数据源
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    useSSL: false
    filters: stat
    maxActive: 20
    initialSize: 5
    maxWait: 60000
    minIdle: 2
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: select 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxOpenPreparedStatements: 20
    #配置监控统计的拦截功能，stat,监控统计，wall，防御sql注入，log4j，日志记录:
    druid:
      filter:
        wall:
          enabled: true
        stat:
          enabled: true
          merge-sql: true
          slow-sql-millis: 5000
        log4j:
          enabled: true
      use-global-data-source-stat: true
      stat-view-servlet:
        enabled: true
    #    login-username: admin
   #     login-password: a123
    #    allow: 127.0.0.1
   #     deny: 192.168.31.28
     #是否开启单个监控url调用的sql列表 默认开启
      web-stat-filter:
        session-stat-enable: true
        enabled: true
        session-stat-max-count: 1000

  #合并多个 数据源
  thymeleaf:
    prefix: classpath:/templates/
    ## 实现页面热部署，修改后立即生效
    cache: false
    suffix: .html
    encoding: utf-8
    servlet:
      content-type: text/html
  ## 热部署生效
  devtools:
    restart:
      enabled: true
      exclude: templates
  application:
    name: boot-client
  # 消息队列配置
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: admin
    password: a123
    #指定连接到broker的virtual host
    virtual-host: /
    #指定最小的消费者数量
    listener:
      simple:
        concurrency: 5
        max-concurrency: 10
        # 指定Acknowledge的模式，我这里是手工确认的
        acknowledge-mode: manual
        # 指定一个请求能处理多少个消息，如果有事务的话，必须大于等于transaction数量
        prefetch: 1
    #指定最大的消费者数量
  #邮件发送的配置
  mail:
    host: smtp.qq.com
    username: 993874575@qq.com
    password: tqrdzuxcdgrobdjh
    default-encoding: UTF-8
  mvc:
    static-path-pattern: /static/**
  resources:
    static-locations: classpath:/static,classpath:/resources
  redis:
    host: 127.0.0.1
    port: 6379
    ## 连接超时时间（毫秒）
    timeout: 300
    password:
    pool:
      #连接池中的最大空闲连接
      max-idle: 10
      # 连接池中的最大连接数
      max-active: 10
      #连接池最大阻塞等待时间（使用负值表示没有限制）
      max-wait: 3
## 该配置节点为独立的节点，容易将这个配置放在spring的节点下，导致配置无法被识别
mybatis:
  mapper-locations: classpath:mapping/**/*.xml #注意：一定要对应mapper映射xml文件的所在路径
  type-aliases-package: com.zys.boot  # 注意：对应实体类的路径

#pagehelper分页插件
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
